name: simulapp
description: "Practice your Michigan, Cambridge and Toelf exams"
publish_to: 'none'
version: 1.0.10+10

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  url_launcher: ^6.3.2
  flutter_event_calendar: ^1.0.0
  google_maps_flutter: ^2.13.1
  location: ^8.0.1
  http: ^1.5.0
  geocoding: ^4.0.0
  intl: ^0.20.2
  provider: ^6.1.5+1
  flutter_dotenv: ^6.0.0
  google_sign_in: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/CAE.jpg
    - assets/images/CPE.jpg
    - assets/images/ECCE.jpg
    - assets/images/ECPE.jpg
    - assets/images/IBT.jpg
    - assets/images/ITP.jpg
    - assets/images/MET.jpg
    - assets/images/google_logo.webp
    - assets/data.json
    - .env
